server:
  port: 8083

spring:
  application:
    name: inventory-service

logging:
  level:
    org.barcodev: INFO

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
