server:
  port: 8083

spring:
  application:
    name: inventory-service

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    template:
      observation-enabled: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      observation-enabled: true
    consumer:
      group-id: inventory-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "org.barcodev.inventoryservice.dto"
        spring.json.use.type.headers: true
        spring.json.type.mapping: "orderEvent:org.barcodev.inventoryservice.dto.OrderEvent"

logging:
  level:
    org.barcodev: INFO
  pattern:
    level: "%5p [traceId=%X{traceId} spanId=%X{spanId} userId=%X{userId} eventId=%X{eventId} correlationId=%X{correlationId}]"

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0 # Sample 100% of requests for dev
  otlp:
    tracing:
      endpoint: ${OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces} # datadog OTLP endpoint
    metrics:
      export:
        url: ${OTLP_METRICS_ENDPOINT:http://localhost:4318/v1/metrics}
        step: 10s
